import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import Header from "@/components/headers/Header";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E Commerce",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
